/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HoldingsRouteImport } from './routes/holdings'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FreeDeliveryRouteImport } from './routes/free-delivery'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CreateCollectionRouteImport } from './routes/create-collection'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BidsRouteImport } from './routes/bids'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as ApplyArtistRouteImport } from './routes/apply-artist'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsProvenanceRouteImport } from './routes/settings.provenance'
import { Route as SettingsCurrencyRouteImport } from './routes/settings.currency'
import { Route as SellCreateRouteImport } from './routes/sell.create'
import { Route as SearchFiltersRouteImport } from './routes/search.filters'
import { Route as ProvenanceIdRouteImport } from './routes/provenance.$id'
import { Route as PortfolioArtworksRouteImport } from './routes/portfolio.artworks'
import { Route as PortfolioAnalyticsRouteImport } from './routes/portfolio.analytics'
import { Route as OnboardingWalletSuccessRouteImport } from './routes/onboarding.wallet-success'
import { Route as OnboardingWalletRouteImport } from './routes/onboarding.wallet'
import { Route as OnboardingStylesRouteImport } from './routes/onboarding.styles'
import { Route as OnboardingSetupRouteImport } from './routes/onboarding.setup'
import { Route as OnboardingGoalsRouteImport } from './routes/onboarding.goals'
import { Route as OnboardingBudgetRouteImport } from './routes/onboarding.budget'
import { Route as MakeOfferIdRouteImport } from './routes/make-offer.$id'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as CollectionIdRouteImport } from './routes/collection.$id'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as AuctionIdRouteImport } from './routes/auction.$id'
import { Route as ArtworkIdRouteImport } from './routes/artwork.$id'
import { Route as ArtistIdRouteImport } from './routes/artist.$id'
import { Route as ArtistIdArtworksRouteImport } from './routes/artist.$id.artworks'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsRoute = HoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeDeliveryRoute = FreeDeliveryRouteImport.update({
  id: '/free-delivery',
  path: '/free-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateCollectionRoute = CreateCollectionRouteImport.update({
  id: '/create-collection',
  path: '/create-collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BidsRoute = BidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyArtistRoute = ApplyArtistRouteImport.update({
  id: '/apply-artist',
  path: '/apply-artist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvenanceRoute = SettingsProvenanceRouteImport.update({
  id: '/provenance',
  path: '/provenance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCurrencyRoute = SettingsCurrencyRouteImport.update({
  id: '/currency',
  path: '/currency',
  getParentRoute: () => SettingsRoute,
} as any)
const SellCreateRoute = SellCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SellRoute,
} as any)
const SearchFiltersRoute = SearchFiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => SearchRoute,
} as any)
const ProvenanceIdRoute = ProvenanceIdRouteImport.update({
  id: '/provenance/$id',
  path: '/provenance/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioArtworksRoute = PortfolioArtworksRouteImport.update({
  id: '/artworks',
  path: '/artworks',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioAnalyticsRoute = PortfolioAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PortfolioRoute,
} as any)
const OnboardingWalletSuccessRoute = OnboardingWalletSuccessRouteImport.update({
  id: '/onboarding/wallet-success',
  path: '/onboarding/wallet-success',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWalletRoute = OnboardingWalletRouteImport.update({
  id: '/onboarding/wallet',
  path: '/onboarding/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStylesRoute = OnboardingStylesRouteImport.update({
  id: '/onboarding/styles',
  path: '/onboarding/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSetupRoute = OnboardingSetupRouteImport.update({
  id: '/onboarding/setup',
  path: '/onboarding/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingGoalsRoute = OnboardingGoalsRouteImport.update({
  id: '/onboarding/goals',
  path: '/onboarding/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBudgetRoute = OnboardingBudgetRouteImport.update({
  id: '/onboarding/budget',
  path: '/onboarding/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeOfferIdRoute = MakeOfferIdRouteImport.update({
  id: '/make-offer/$id',
  path: '/make-offer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIdRoute = CollectionIdRouteImport.update({
  id: '/collection/$id',
  path: '/collection/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const AuctionIdRoute = AuctionIdRouteImport.update({
  id: '/auction/$id',
  path: '/auction/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworkIdRoute = ArtworkIdRouteImport.update({
  id: '/artwork/$id',
  path: '/artwork/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIdRoute = ArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIdArtworksRoute = ArtistIdArtworksRouteImport.update({
  id: '/artworks',
  path: '/artworks',
  getParentRoute: () => ArtistIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/apply-artist': typeof ApplyArtistRoute
  '/artists': typeof ArtistsRoute
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/bids': typeof BidsRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/community': typeof CommunityRoute
  '/create-collection': typeof CreateCollectionRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/free-delivery': typeof FreeDeliveryRoute
  '/help': typeof HelpRoute
  '/holdings': typeof HoldingsRoute
  '/home': typeof HomeRoute
  '/inbox': typeof InboxRoute
  '/invite': typeof InviteRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRouteWithChildren
  '/sell': typeof SellRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/trending': typeof TrendingRoute
  '/two-factor': typeof TwoFactorRoute
  '/upload': typeof UploadRoute
  '/vault': typeof VaultRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wallet': typeof WalletRoute
  '/watchlist': typeof WatchlistRoute
  '/artist/$id': typeof ArtistIdRouteWithChildren
  '/artwork/$id': typeof ArtworkIdRoute
  '/auction/$id': typeof AuctionIdRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collection/$id': typeof CollectionIdRoute
  '/event/$id': typeof EventIdRoute
  '/make-offer/$id': typeof MakeOfferIdRoute
  '/onboarding/budget': typeof OnboardingBudgetRoute
  '/onboarding/goals': typeof OnboardingGoalsRoute
  '/onboarding/setup': typeof OnboardingSetupRoute
  '/onboarding/styles': typeof OnboardingStylesRoute
  '/onboarding/wallet': typeof OnboardingWalletRoute
  '/onboarding/wallet-success': typeof OnboardingWalletSuccessRoute
  '/portfolio/analytics': typeof PortfolioAnalyticsRoute
  '/portfolio/artworks': typeof PortfolioArtworksRoute
  '/provenance/$id': typeof ProvenanceIdRoute
  '/search/filters': typeof SearchFiltersRoute
  '/sell/create': typeof SellCreateRoute
  '/settings/currency': typeof SettingsCurrencyRoute
  '/settings/provenance': typeof SettingsProvenanceRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/artist/$id/artworks': typeof ArtistIdArtworksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/apply-artist': typeof ApplyArtistRoute
  '/artists': typeof ArtistsRoute
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/bids': typeof BidsRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/community': typeof CommunityRoute
  '/create-collection': typeof CreateCollectionRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/free-delivery': typeof FreeDeliveryRoute
  '/help': typeof HelpRoute
  '/holdings': typeof HoldingsRoute
  '/home': typeof HomeRoute
  '/inbox': typeof InboxRoute
  '/invite': typeof InviteRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRouteWithChildren
  '/sell': typeof SellRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/trending': typeof TrendingRoute
  '/two-factor': typeof TwoFactorRoute
  '/upload': typeof UploadRoute
  '/vault': typeof VaultRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wallet': typeof WalletRoute
  '/watchlist': typeof WatchlistRoute
  '/artist/$id': typeof ArtistIdRouteWithChildren
  '/artwork/$id': typeof ArtworkIdRoute
  '/auction/$id': typeof AuctionIdRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collection/$id': typeof CollectionIdRoute
  '/event/$id': typeof EventIdRoute
  '/make-offer/$id': typeof MakeOfferIdRoute
  '/onboarding/budget': typeof OnboardingBudgetRoute
  '/onboarding/goals': typeof OnboardingGoalsRoute
  '/onboarding/setup': typeof OnboardingSetupRoute
  '/onboarding/styles': typeof OnboardingStylesRoute
  '/onboarding/wallet': typeof OnboardingWalletRoute
  '/onboarding/wallet-success': typeof OnboardingWalletSuccessRoute
  '/portfolio/analytics': typeof PortfolioAnalyticsRoute
  '/portfolio/artworks': typeof PortfolioArtworksRoute
  '/provenance/$id': typeof ProvenanceIdRoute
  '/search/filters': typeof SearchFiltersRoute
  '/sell/create': typeof SellCreateRoute
  '/settings/currency': typeof SettingsCurrencyRoute
  '/settings/provenance': typeof SettingsProvenanceRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/artist/$id/artworks': typeof ArtistIdArtworksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/apply-artist': typeof ApplyArtistRoute
  '/artists': typeof ArtistsRoute
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/bids': typeof BidsRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/community': typeof CommunityRoute
  '/create-collection': typeof CreateCollectionRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/free-delivery': typeof FreeDeliveryRoute
  '/help': typeof HelpRoute
  '/holdings': typeof HoldingsRoute
  '/home': typeof HomeRoute
  '/inbox': typeof InboxRoute
  '/invite': typeof InviteRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRouteWithChildren
  '/sell': typeof SellRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/trending': typeof TrendingRoute
  '/two-factor': typeof TwoFactorRoute
  '/upload': typeof UploadRoute
  '/vault': typeof VaultRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wallet': typeof WalletRoute
  '/watchlist': typeof WatchlistRoute
  '/artist/$id': typeof ArtistIdRouteWithChildren
  '/artwork/$id': typeof ArtworkIdRoute
  '/auction/$id': typeof AuctionIdRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collection/$id': typeof CollectionIdRoute
  '/event/$id': typeof EventIdRoute
  '/make-offer/$id': typeof MakeOfferIdRoute
  '/onboarding/budget': typeof OnboardingBudgetRoute
  '/onboarding/goals': typeof OnboardingGoalsRoute
  '/onboarding/setup': typeof OnboardingSetupRoute
  '/onboarding/styles': typeof OnboardingStylesRoute
  '/onboarding/wallet': typeof OnboardingWalletRoute
  '/onboarding/wallet-success': typeof OnboardingWalletSuccessRoute
  '/portfolio/analytics': typeof PortfolioAnalyticsRoute
  '/portfolio/artworks': typeof PortfolioArtworksRoute
  '/provenance/$id': typeof ProvenanceIdRoute
  '/search/filters': typeof SearchFiltersRoute
  '/sell/create': typeof SellCreateRoute
  '/settings/currency': typeof SettingsCurrencyRoute
  '/settings/provenance': typeof SettingsProvenanceRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/artist/$id/artworks': typeof ArtistIdArtworksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activity'
    | '/admin'
    | '/apply-artist'
    | '/artists'
    | '/auctions'
    | '/auth'
    | '/bids'
    | '/checkout'
    | '/collections'
    | '/community'
    | '/create-collection'
    | '/events'
    | '/explore'
    | '/favorites'
    | '/forgot-password'
    | '/free-delivery'
    | '/help'
    | '/holdings'
    | '/home'
    | '/inbox'
    | '/invite'
    | '/messages'
    | '/notifications'
    | '/offers'
    | '/portfolio'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/sell'
    | '/settings'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
    | '/transactions'
    | '/trending'
    | '/two-factor'
    | '/upload'
    | '/vault'
    | '/verify-email'
    | '/wallet'
    | '/watchlist'
    | '/artist/$id'
    | '/artwork/$id'
    | '/auction/$id'
    | '/checkout/success'
    | '/collection/$id'
    | '/event/$id'
    | '/make-offer/$id'
    | '/onboarding/budget'
    | '/onboarding/goals'
    | '/onboarding/setup'
    | '/onboarding/styles'
    | '/onboarding/wallet'
    | '/onboarding/wallet-success'
    | '/portfolio/analytics'
    | '/portfolio/artworks'
    | '/provenance/$id'
    | '/search/filters'
    | '/sell/create'
    | '/settings/currency'
    | '/settings/provenance'
    | '/settings/security'
    | '/artist/$id/artworks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activity'
    | '/admin'
    | '/apply-artist'
    | '/artists'
    | '/auctions'
    | '/auth'
    | '/bids'
    | '/checkout'
    | '/collections'
    | '/community'
    | '/create-collection'
    | '/events'
    | '/explore'
    | '/favorites'
    | '/forgot-password'
    | '/free-delivery'
    | '/help'
    | '/holdings'
    | '/home'
    | '/inbox'
    | '/invite'
    | '/messages'
    | '/notifications'
    | '/offers'
    | '/portfolio'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/sell'
    | '/settings'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
    | '/transactions'
    | '/trending'
    | '/two-factor'
    | '/upload'
    | '/vault'
    | '/verify-email'
    | '/wallet'
    | '/watchlist'
    | '/artist/$id'
    | '/artwork/$id'
    | '/auction/$id'
    | '/checkout/success'
    | '/collection/$id'
    | '/event/$id'
    | '/make-offer/$id'
    | '/onboarding/budget'
    | '/onboarding/goals'
    | '/onboarding/setup'
    | '/onboarding/styles'
    | '/onboarding/wallet'
    | '/onboarding/wallet-success'
    | '/portfolio/analytics'
    | '/portfolio/artworks'
    | '/provenance/$id'
    | '/search/filters'
    | '/sell/create'
    | '/settings/currency'
    | '/settings/provenance'
    | '/settings/security'
    | '/artist/$id/artworks'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activity'
    | '/admin'
    | '/apply-artist'
    | '/artists'
    | '/auctions'
    | '/auth'
    | '/bids'
    | '/checkout'
    | '/collections'
    | '/community'
    | '/create-collection'
    | '/events'
    | '/explore'
    | '/favorites'
    | '/forgot-password'
    | '/free-delivery'
    | '/help'
    | '/holdings'
    | '/home'
    | '/inbox'
    | '/invite'
    | '/messages'
    | '/notifications'
    | '/offers'
    | '/portfolio'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/sell'
    | '/settings'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
    | '/transactions'
    | '/trending'
    | '/two-factor'
    | '/upload'
    | '/vault'
    | '/verify-email'
    | '/wallet'
    | '/watchlist'
    | '/artist/$id'
    | '/artwork/$id'
    | '/auction/$id'
    | '/checkout/success'
    | '/collection/$id'
    | '/event/$id'
    | '/make-offer/$id'
    | '/onboarding/budget'
    | '/onboarding/goals'
    | '/onboarding/setup'
    | '/onboarding/styles'
    | '/onboarding/wallet'
    | '/onboarding/wallet-success'
    | '/portfolio/analytics'
    | '/portfolio/artworks'
    | '/provenance/$id'
    | '/search/filters'
    | '/sell/create'
    | '/settings/currency'
    | '/settings/provenance'
    | '/settings/security'
    | '/artist/$id/artworks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivityRoute: typeof ActivityRoute
  AdminRoute: typeof AdminRoute
  ApplyArtistRoute: typeof ApplyArtistRoute
  ArtistsRoute: typeof ArtistsRoute
  AuctionsRoute: typeof AuctionsRoute
  AuthRoute: typeof AuthRoute
  BidsRoute: typeof BidsRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CollectionsRoute: typeof CollectionsRoute
  CommunityRoute: typeof CommunityRoute
  CreateCollectionRoute: typeof CreateCollectionRoute
  EventsRoute: typeof EventsRoute
  ExploreRoute: typeof ExploreRoute
  FavoritesRoute: typeof FavoritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FreeDeliveryRoute: typeof FreeDeliveryRoute
  HelpRoute: typeof HelpRoute
  HoldingsRoute: typeof HoldingsRoute
  HomeRoute: typeof HomeRoute
  InboxRoute: typeof InboxRoute
  InviteRoute: typeof InviteRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRouteWithChildren
  SellRoute: typeof SellRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  ShippingRoute: typeof ShippingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TransactionsRoute: typeof TransactionsRoute
  TrendingRoute: typeof TrendingRoute
  TwoFactorRoute: typeof TwoFactorRoute
  UploadRoute: typeof UploadRoute
  VaultRoute: typeof VaultRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WalletRoute: typeof WalletRoute
  WatchlistRoute: typeof WatchlistRoute
  ArtistIdRoute: typeof ArtistIdRouteWithChildren
  ArtworkIdRoute: typeof ArtworkIdRoute
  AuctionIdRoute: typeof AuctionIdRoute
  CollectionIdRoute: typeof CollectionIdRoute
  EventIdRoute: typeof EventIdRoute
  MakeOfferIdRoute: typeof MakeOfferIdRoute
  OnboardingBudgetRoute: typeof OnboardingBudgetRoute
  OnboardingGoalsRoute: typeof OnboardingGoalsRoute
  OnboardingSetupRoute: typeof OnboardingSetupRoute
  OnboardingStylesRoute: typeof OnboardingStylesRoute
  OnboardingWalletRoute: typeof OnboardingWalletRoute
  OnboardingWalletSuccessRoute: typeof OnboardingWalletSuccessRoute
  ProvenanceIdRoute: typeof ProvenanceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings': {
      id: '/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof HoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-delivery': {
      id: '/free-delivery'
      path: '/free-delivery'
      fullPath: '/free-delivery'
      preLoaderRoute: typeof FreeDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-collection': {
      id: '/create-collection'
      path: '/create-collection'
      fullPath: '/create-collection'
      preLoaderRoute: typeof CreateCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bids': {
      id: '/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof BidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-artist': {
      id: '/apply-artist'
      path: '/apply-artist'
      fullPath: '/apply-artist'
      preLoaderRoute: typeof ApplyArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/provenance': {
      id: '/settings/provenance'
      path: '/provenance'
      fullPath: '/settings/provenance'
      preLoaderRoute: typeof SettingsProvenanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/currency': {
      id: '/settings/currency'
      path: '/currency'
      fullPath: '/settings/currency'
      preLoaderRoute: typeof SettingsCurrencyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/sell/create': {
      id: '/sell/create'
      path: '/create'
      fullPath: '/sell/create'
      preLoaderRoute: typeof SellCreateRouteImport
      parentRoute: typeof SellRoute
    }
    '/search/filters': {
      id: '/search/filters'
      path: '/filters'
      fullPath: '/search/filters'
      preLoaderRoute: typeof SearchFiltersRouteImport
      parentRoute: typeof SearchRoute
    }
    '/provenance/$id': {
      id: '/provenance/$id'
      path: '/provenance/$id'
      fullPath: '/provenance/$id'
      preLoaderRoute: typeof ProvenanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/artworks': {
      id: '/portfolio/artworks'
      path: '/artworks'
      fullPath: '/portfolio/artworks'
      preLoaderRoute: typeof PortfolioArtworksRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/analytics': {
      id: '/portfolio/analytics'
      path: '/analytics'
      fullPath: '/portfolio/analytics'
      preLoaderRoute: typeof PortfolioAnalyticsRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/onboarding/wallet-success': {
      id: '/onboarding/wallet-success'
      path: '/onboarding/wallet-success'
      fullPath: '/onboarding/wallet-success'
      preLoaderRoute: typeof OnboardingWalletSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/wallet': {
      id: '/onboarding/wallet'
      path: '/onboarding/wallet'
      fullPath: '/onboarding/wallet'
      preLoaderRoute: typeof OnboardingWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/styles': {
      id: '/onboarding/styles'
      path: '/onboarding/styles'
      fullPath: '/onboarding/styles'
      preLoaderRoute: typeof OnboardingStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/setup': {
      id: '/onboarding/setup'
      path: '/onboarding/setup'
      fullPath: '/onboarding/setup'
      preLoaderRoute: typeof OnboardingSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/goals': {
      id: '/onboarding/goals'
      path: '/onboarding/goals'
      fullPath: '/onboarding/goals'
      preLoaderRoute: typeof OnboardingGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/budget': {
      id: '/onboarding/budget'
      path: '/onboarding/budget'
      fullPath: '/onboarding/budget'
      preLoaderRoute: typeof OnboardingBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make-offer/$id': {
      id: '/make-offer/$id'
      path: '/make-offer/$id'
      fullPath: '/make-offer/$id'
      preLoaderRoute: typeof MakeOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$id': {
      id: '/collection/$id'
      path: '/collection/$id'
      fullPath: '/collection/$id'
      preLoaderRoute: typeof CollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/auction/$id': {
      id: '/auction/$id'
      path: '/auction/$id'
      fullPath: '/auction/$id'
      preLoaderRoute: typeof AuctionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artwork/$id': {
      id: '/artwork/$id'
      path: '/artwork/$id'
      fullPath: '/artwork/$id'
      preLoaderRoute: typeof ArtworkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$id': {
      id: '/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof ArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$id/artworks': {
      id: '/artist/$id/artworks'
      path: '/artworks'
      fullPath: '/artist/$id/artworks'
      preLoaderRoute: typeof ArtistIdArtworksRouteImport
      parentRoute: typeof ArtistIdRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface PortfolioRouteChildren {
  PortfolioAnalyticsRoute: typeof PortfolioAnalyticsRoute
  PortfolioArtworksRoute: typeof PortfolioArtworksRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioAnalyticsRoute: PortfolioAnalyticsRoute,
  PortfolioArtworksRoute: PortfolioArtworksRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface SearchRouteChildren {
  SearchFiltersRoute: typeof SearchFiltersRoute
}

const SearchRouteChildren: SearchRouteChildren = {
  SearchFiltersRoute: SearchFiltersRoute,
}

const SearchRouteWithChildren =
  SearchRoute._addFileChildren(SearchRouteChildren)

interface SellRouteChildren {
  SellCreateRoute: typeof SellCreateRoute
}

const SellRouteChildren: SellRouteChildren = {
  SellCreateRoute: SellCreateRoute,
}

const SellRouteWithChildren = SellRoute._addFileChildren(SellRouteChildren)

interface SettingsRouteChildren {
  SettingsCurrencyRoute: typeof SettingsCurrencyRoute
  SettingsProvenanceRoute: typeof SettingsProvenanceRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCurrencyRoute: SettingsCurrencyRoute,
  SettingsProvenanceRoute: SettingsProvenanceRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ArtistIdRouteChildren {
  ArtistIdArtworksRoute: typeof ArtistIdArtworksRoute
}

const ArtistIdRouteChildren: ArtistIdRouteChildren = {
  ArtistIdArtworksRoute: ArtistIdArtworksRoute,
}

const ArtistIdRouteWithChildren = ArtistIdRoute._addFileChildren(
  ArtistIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivityRoute: ActivityRoute,
  AdminRoute: AdminRoute,
  ApplyArtistRoute: ApplyArtistRoute,
  ArtistsRoute: ArtistsRoute,
  AuctionsRoute: AuctionsRoute,
  AuthRoute: AuthRoute,
  BidsRoute: BidsRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CollectionsRoute: CollectionsRoute,
  CommunityRoute: CommunityRoute,
  CreateCollectionRoute: CreateCollectionRoute,
  EventsRoute: EventsRoute,
  ExploreRoute: ExploreRoute,
  FavoritesRoute: FavoritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FreeDeliveryRoute: FreeDeliveryRoute,
  HelpRoute: HelpRoute,
  HoldingsRoute: HoldingsRoute,
  HomeRoute: HomeRoute,
  InboxRoute: InboxRoute,
  InviteRoute: InviteRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRouteWithChildren,
  SellRoute: SellRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  ShippingRoute: ShippingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TransactionsRoute: TransactionsRoute,
  TrendingRoute: TrendingRoute,
  TwoFactorRoute: TwoFactorRoute,
  UploadRoute: UploadRoute,
  VaultRoute: VaultRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WalletRoute: WalletRoute,
  WatchlistRoute: WatchlistRoute,
  ArtistIdRoute: ArtistIdRouteWithChildren,
  ArtworkIdRoute: ArtworkIdRoute,
  AuctionIdRoute: AuctionIdRoute,
  CollectionIdRoute: CollectionIdRoute,
  EventIdRoute: EventIdRoute,
  MakeOfferIdRoute: MakeOfferIdRoute,
  OnboardingBudgetRoute: OnboardingBudgetRoute,
  OnboardingGoalsRoute: OnboardingGoalsRoute,
  OnboardingSetupRoute: OnboardingSetupRoute,
  OnboardingStylesRoute: OnboardingStylesRoute,
  OnboardingWalletRoute: OnboardingWalletRoute,
  OnboardingWalletSuccessRoute: OnboardingWalletSuccessRoute,
  ProvenanceIdRoute: ProvenanceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
